"""Add Newtable and other models

Revision ID: 31900876ba1c
Revises: 83b173437582
Create Date: 2024-11-24 15:45:16.101762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31900876ba1c'
down_revision = '83b173437582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_post', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
