"""Fix models and add Newtable

Revision ID: de66d4490da8
Revises: f524a8545d82
Create Date: 2024-11-24 10:33:47.196475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de66d4490da8'
down_revision = 'f524a8545d82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('newtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num_columns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('db1324')
    op.drop_table('db1')
    op.drop_table('Database1')
    op.drop_table('db3')
    op.drop_table('db6')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db6',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_5', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_6', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='db6_pkey')
    )
    op.create_table('db3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_5', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_6', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_7', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_8', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_9', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='db3_pkey')
    )
    op.create_table('Database1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Database1_pkey')
    )
    op.create_table('db1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='db1_pkey')
    )
    op.create_table('db1324',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('column_1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('column_5', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='db1324_pkey')
    )
    op.drop_table('newtable')
    # ### end Alembic commands ###
